export interface Site {
    id: number;
    host: string;
    name: string;
    upstream_url: string;
    is_active: boolean;
    preserve_host_header: boolean;
    enable_sni: boolean;
    websocket_enabled: boolean;
    sse_enabled: boolean;
    body_inspection_profile: string;
    client_max_body_size_mb: number | null;
    proxy_request_buffering: boolean | null;
    proxy_read_timeout_sec: number;
    proxy_send_timeout_sec: number;
    proxy_connect_timeout_sec: number;
    proxy_redirect_mode: 'default' | 'off' | 'rewrite_to_public_host';
    cookie_rewrite_enabled: boolean;
    waf_decision_mode: 'fail_open' | 'fail_close';
    tls_enabled: boolean;
    http_redirect_to_https: boolean;
    tls_certificate_id: number | null;
    upstream_tls_verify: boolean;
    upstream_tls_server_name_override: string | null;
    hsts_enabled: boolean;
    xss_enabled: boolean;
    sql_enabled: boolean;
    vt_enabled: boolean;
    health_status?: 'healthy' | 'unhealthy' | 'unknown';
    resolved_upstream_ips?: string[] | null;
    last_resolved_at?: string | null;
}

export interface SiteCreate {
    host: string;
    name: string;
    upstream_url: string;
    is_active: boolean;
    preserve_host_header: boolean;
    enable_sni: boolean;
    websocket_enabled: boolean;
    sse_enabled: boolean;
    body_inspection_profile: string;
    client_max_body_size_mb: number | null;
    proxy_request_buffering: boolean | null;
    proxy_read_timeout_sec: number;
    proxy_send_timeout_sec: number;
    proxy_connect_timeout_sec: number;
    proxy_redirect_mode: 'default' | 'off' | 'rewrite_to_public_host';
    cookie_rewrite_enabled: boolean;
    waf_decision_mode: 'fail_open' | 'fail_close';
    tls_enabled: boolean;
    http_redirect_to_https: boolean;
    tls_certificate_id: number | null;
    upstream_tls_verify: boolean;
    upstream_tls_server_name_override: string | null;
    hsts_enabled: boolean;
    xss_enabled: boolean;
    sql_enabled: boolean;
    vt_enabled: boolean;
}
